name: generate ascii artwork through shell script

on: push

jobs:
    first_jb:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          name: clone repo
        - name: list files
          run: ls -ltra
        - name: execute gen_ascii shell script
          run: ./gen_ascii.sh 
